---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
        - name: flux-test
          image: openebs/flux-test:master-000004
          ports:
            - containerPort: 8080
 
