---
apiVersion: harness.io/v1alpha1
kind: runbook
metadata: 
  name: verify-microservice-health
  labels:
    type: triage
    platform: kubernetes
  annotations:
    source: |
      {"runbookHubId": "kubernetes-kb", "kbId": "kb101"} 
  spec: 
    owners:
      users: "sagar.kr@harness.io, raj.das@harness.io"
      userGroups: "" 
    actions:
      - name: check-deployment-resources-on-the-cluster
        owner: "karthik.s@harness.io"
        approvers: 
          users: ""
          userGroups: "cloud-engg"
          minApprovalCount: 2
        provider: harness 
        connector: ""  
        type: manual
        spec:
          taskItems:
            - name: check-pod-phase-for-deployment-replicas
            - name: check-container-readiness-for-replica-containers
          

             

            
    
  
    
    
    
