# provide the memory pecentage to stress the instance memory
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: aws-ssm-chaos-by-id-sa
  experiments:
  - name: aws-ssm-chaos-by-id
    specEC2_INSTANCE_ID:
      components:
        env:
        # memory percentage for the stress
        - name: MEMORY_PERCENTAGE
          value: '80'
        # id of the ec2 instance
        - name: EC2_INSTANCE_ID
          value: 'instance-01'
        # region of the ec2 instance
        - name: REGION
          value: '<region of the EC2_INSTANCE_ID>'
        - name: TOTAL_CHAOS_DURATION
          VALUE: '60'
