apiVersion: batch/v1
kind: Job
metadata:
  generateName: event-feeder-job-prereq-
  namespace: "shubhamch"
spec:
  template:
    metadata:
      labels:
        app: event-feeder
    spec:
      containers:
      - image: shubh214/event-feeder:1.3.0
        name: event-feeder
        env:
          - name: RAMP_TIME
            value: "1"
          - name: INTERVAL
            value: "1"
          - name: ENVIRONMENT_ID
            value: "test"
          - name: SOURCE
            value: "K8sWatcher"
          - name: INFRA_ID
            value: "prodecommerce"
        envFrom:
          - secretRef:
              name: event-feeder
        resources: {}
      restartPolicy: OnFailure  # Jobs typically use OnFailure or Never
  backoffLimit: 2  # Maximum number of retries before the job is considered failed
