apiVersion: batch/v1
kind: Job
metadata:
  generateName: event-feeder-job-post-
spec:
  template:
    metadata:
      labels:
        app: event-feeder
    spec:
      containers:
      - image: shubh214/event-feeder:1.6.0
        name: event-feeder
        env:
          - name: RAMP_TIME
            value: "10"
          - name: INTERVAL
            value: "4"
          - name: ENVIRONMENT_ID
            value: "test"
          - name: SOURCE
            value: "K8sWatcher"
          - name: INFRA_ID
            value: "prodpodtato"
        envFrom:
          - secretRef:
              name: event-feeder
        resources: {}
      restartPolicy: OnFailure  # Jobs typically use OnFailure or Never
  backoffLimit: 2  # Maximum number of retries before the job is considered failed
