apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: greetflow
spec:
  entrypoint: greet
  serviceAccountName: argo-chaos-default
  templates:
  - name: greet
    steps:
    - - name: hello
        template: hello
  - name: hello
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"Hi, it is a demo!\"; sleep 60"]
