{
 "title": "Node  Stats",
 "description": "This for the Node Exporter version 0.16.0 or later.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"node\"}"
   }
  ]
 },
 "panels": [
  { "title": "Node Filesystem Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"$instance\",mountpoint=~\"/\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Root partition usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$instance\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Currently Open File Descriptor",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mounted Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\",mountpoint!~\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$instance\",mountpoint!~\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Node CPU, Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\"}) without (mode,instance,job)) without (cpu) "
      }
     ]
    },
    {
     "title": "Memory Stats ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 2, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
       "legendFormat": "Total memory"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "CPU Stats",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"system\"}[1m]))",
       "legendFormat": "system "
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"user\"}[1m]))",
       "legendFormat": "user"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[1m]))",
       "legendFormat": "idle"
      },
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{device}}_% of I/O operations per second"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[1m]))",
       "legendFormat": "iowait"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance\"}",
       "legendFormat": "1 Min"
      },
      {
       "expr": "node_load5{instance=~\"$instance\"}",
       "legendFormat": "5 Min"
      },
      {
       "expr": "node_load15{instance=~\"$instance\"}",
       "legendFormat": "15 Min"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "Context Switches"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Transmitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\",device!~\"lo\"}[5m])",
       "legendFormat": "{{device}} out"
      }
     ]
    },
    {
     "title": "Network Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\",device!~\"lo\"}[5m])",
       "legendFormat": "{{device}} in"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Disk Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization per Device",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~'$instance',device!~'^(md\\\\\\\\d+$|dm-)'}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Writes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "IO Wait Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(node_disk_write_time_seconds_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])/increase(node_disk_writes_completed_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(node_disk_read_time_seconds_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])/increase(node_disk_reads_completed_total{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}