# power-off the vmware vm
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  chaosServiceAccount: vm-poweroff-sa
  experiments:
  - name: vm-poweroff
    spec:
      components:
        env:
        # moid of the vm instance
        - name: APP_VM_MOID
          value: 'vm-5365'
        - name: TOTAL_CHAOS_DURATION
          VALUE: '60'
